In [1]:
import tensorflow as tf
from tensorflow.keras import layers

x = tf.range(10)  # 產生10個單詞的index
# 創建 10 個單詞, 每個單詞長度為 3 的 Word Embedding層
embeddingnet = layers.Embedding(10,3)
out = embeddingnet(x)
print(out)

tf.Tensor(
[[-0.02692045  0.04263074 -0.01862876]
 [-0.04253326 -0.00458181 -0.01855283]
 [-0.00938035 -0.04965532 -0.04530683]
 [ 0.04530979 -0.01605215 -0.0190699 ]
 [ 0.02036682  0.02531332  0.04678765]
 [-0.00997264  0.00012172 -0.03951764]
 [-0.03516417  0.0450256   0.00822349]
 [-0.01668031 -0.01254394 -0.00631505]
 [ 0.023479   -0.00376706 -0.00397446]
 [-0.02415398  0.01911185 -0.00171412]], shape=(10, 3), dtype=float32)


In [2]:
# 得到 embedding 層參數
print(embeddingnet.embeddings)
# 查看參數是否是可以訓練的
print(embeddingnet.embeddings.trainable)

<tf.Variable 'embedding/embeddings:0' shape=(10, 3) dtype=float32, numpy=
array([[-0.02692045,  0.04263074, -0.01862876],
       [-0.04253326, -0.00458181, -0.01855283],
       [-0.00938035, -0.04965532, -0.04530683],
       [ 0.04530979, -0.01605215, -0.0190699 ],
       [ 0.02036682,  0.02531332,  0.04678765],
       [-0.00997264,  0.00012172, -0.03951764],
       [-0.03516417,  0.0450256 ,  0.00822349],
       [-0.01668031, -0.01254394, -0.00631505],
       [ 0.023479  , -0.00376706, -0.00397446],
       [-0.02415398,  0.01911185, -0.00171412]], dtype=float32)>
True
