In [2]:
import tensorflow as tf
from tensorflow.keras import layers
# 建立兩個句子, 每個句子10個單詞
word = tf.random.normal([2,10,20])
x0 = word[:,0,:]   # 取第一個時間戳的輸入 x0
# 構建 2 個 Cell,下面為 cell_0,上面為 cell_1，狀態向量長度都為 16
cell_0 = layers.SimpleRNNCell(16)
cell_1 = layers.SimpleRNNCell(16)
h0 = [tf.zeros([2,16])]   # cell0 的初始狀態向量
h1 = [tf.zeros([2,16])]   # cell1 的初始狀態向量
# 保存第一層所有時間步上的輸出
outLevel1 = []
# 計算第一層的所有時間步的前向計算
for x1 in tf.unstack(word, axis=1):
    # xt 作為輸入，輸出為 out0
    out0, h0 = cell_0(x1, h0)
    outLevel1.append(out0)

# 計算第二層的所有時間步的前向計算
for m1 in outLevel1:
    # xt 作為輸入，輸出為 out1
    out1, h1 = cell_1(m1, h1)
    print(out1)

tf.Tensor(
[[ 0.46207616 -0.24459246 -0.48374897  0.2079792  -0.6238907   0.46957082
  -0.62462467 -0.8200683   0.39058262  0.35056838  0.7929097   0.8221315
  -0.18619882  0.68300873 -0.3498117   0.38185894]
 [-0.32289043 -0.17207652  0.8695281  -0.6884199   0.6988029   0.18331715
  -0.28702623  0.95610815 -0.480746    0.6225848  -0.10025231 -0.7925934
   0.4053021  -0.4333408   0.62704635  0.3047453 ]], shape=(2, 16), dtype=float32)
tf.Tensor(
[[ 0.20426005  0.34618768 -0.8456093   0.11246533 -0.16523823  0.6178782
  -0.7904674  -0.49329373 -0.20898609 -0.08757723  0.20093788  0.73086566
  -0.4232991  -0.83571166 -0.9389445  -0.18726027]
 [-0.09432692  0.6980506   0.28192252 -0.00134396  0.11682235  0.20157161
   0.96131563 -0.16252837 -0.74813235 -0.95761615 -0.8069798   0.6674107
   0.55711836 -0.5876475  -0.07562987  0.29080284]], shape=(2, 16), dtype=float32)
tf.Tensor(
[[-0.5134281  -0.88022226  0.7669996  -0.74833924 -0.6841855   0.46291783
  -0.79016274  0.4360626  -0.83605725